---
# handlers file for vector-role
# handlers для старта/рестарта сервиса Vector
- name: Start Vector service
  become: true
  ansible.builtin.systemd:
    name: vector
    state: restarted
  when: ansible_facts.virtualization_type != "docker"